package trip.one.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import trip.one.beans.XingyiTestDO;
import trip.one.beans.XingyiTestDOExample;

public interface XingyiTestDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    long countByExample(XingyiTestDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    int deleteByExample(XingyiTestDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    int insert(XingyiTestDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    int insertSelective(XingyiTestDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    List<XingyiTestDO> selectByExample(XingyiTestDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    XingyiTestDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    int updateByExampleSelective(@Param("row") XingyiTestDO row, @Param("example") XingyiTestDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    int updateByExample(@Param("row") XingyiTestDO row, @Param("example") XingyiTestDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    int updateByPrimaryKeySelective(XingyiTestDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingyi_test
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    int updateByPrimaryKey(XingyiTestDO row);
}