server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/btrip_one?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Wl555888#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=trip.one.beans
mybatis.configuration.map-underscore-to-camel-case=true
