package trip.one.beans;

import java.util.Date;

public class XingyiTestDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xingyi_test.id
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xingyi_test.gmt_create
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xingyi_test.gmt_modified
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xingyi_test.corp_id
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xingyi_test.corp_name
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    private String corpName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xingyi_test.id
     *
     * @return the value of xingyi_test.id
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xingyi_test.id
     *
     * @param id the value for xingyi_test.id
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xingyi_test.gmt_create
     *
     * @return the value of xingyi_test.gmt_create
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xingyi_test.gmt_create
     *
     * @param gmtCreate the value for xingyi_test.gmt_create
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xingyi_test.gmt_modified
     *
     * @return the value of xingyi_test.gmt_modified
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xingyi_test.gmt_modified
     *
     * @param gmtModified the value for xingyi_test.gmt_modified
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xingyi_test.corp_id
     *
     * @return the value of xingyi_test.corp_id
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xingyi_test.corp_id
     *
     * @param corpId the value for xingyi_test.corp_id
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId == null ? null : corpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xingyi_test.corp_name
     *
     * @return the value of xingyi_test.corp_name
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xingyi_test.corp_name
     *
     * @param corpName the value for xingyi_test.corp_name
     *
     * @mbg.generated Sun Jun 07 01:05:50 CST 2026
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }
}